.PHONY: clean All

All:
	@echo "----------Building project:[ BasicIO - Debug ]----------"
	@cd "io" && "$(MAKE)" -f  "BasicIO.mk"
clean:
	@echo "----------Cleaning project:[ BasicIO - Debug ]----------"
	@cd "io" && "$(MAKE)" -f  "BasicIO.mk" clean
